version: "3"
services:
        elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
                container_name: elasticsearch
                environment:
                        - discovery.type=single-node
                volumes:
                        - esdata1:/usr/share/elasticsearch/data
                ports:
                        - "9200:9200"
                network_mode: host
        natlas-server:
                #build: ./natlas-server
                image: jacobtfowler/natlas-server:test
                ports:
                       - "5000:5000"
                # volumes:
                #        - "/var/lib/docker/volumes/metadata.db:/natlas-server/metadata.db"
                depends_on:
                       - elasticsearch
                network_mode: host


networks:
        natlasnet:
                external: true

volumes:
    esdata1:
        driver: local
